### ISSUE TITLE
Will there ever be a linux version or wine support?

### ISSUE THREAD

**Issue by snarkyllama** [tge-was-taken/Mod-Compendium#13]

**Comment by ThisNekoGuy** [comment]
I would like to know too, because the xDelta patcher doesn't work properly in Wine on Linux (it crashes) and none of your tools run in Wine on Linux either

(I tried running it with C# mono, because it's a Windows Forms program, but that didn't work either; running Amacitia in mono "works" but it basically renders as almost completely whitespace with only a File Open button available)

![Screenshot_20191126_230435](https://user-images.githubusercontent.com/28468662/69695283-621bf580-10a1-11ea-826d-4b87395ac31a.png)

**Comment by NerduMiner** [comment]
I have used Amicitia on linux(Linux Mint 19.2) with a 32 bit prefix of wine and it does indeed work(it normally is just whitespace on startup). However trying to use Mod-Compendium with the same method causes an error screen to pop up. The window doesn't properly render however so I can't say what's the issue.
![image](https://user-images.githubusercontent.com/23490112/69736353-4b58bb80-1100-11ea-973e-015d0ecd02ea.png)

**Comment by tge-was-taken** [comment]
Mono does not support wpf. You'd have better luck trying to install the native .NET runtime on wine however I cant help you with that.

**Comment by staticnation** [comment]
I got this working one launch and have been trying to reproduce the steps needed, it involved running in a wine32 prefix, installing net framework with winetricks (crossover installed net 2.0 first so I'm looking into this as well) and using gallium 9 standalone and wine staging, I'll post the steps I took once I get it working again

**Comment by staticnation** [comment]
WINEPREFIX=/path/here winetricks dotnet48

Note: I haven't tested this to see if it will solve the issue, just giving advice on how to install .Net into a wine prefix

**Comment by nonetrix** [comment]
well time to fire up a windows vm I hate my life and bill gates killed my dog irl no homo

**Comment by ShrineFox** [comment]
There is this unofficial build, I don’t know how well it works as it was never finished, and of course a bit outdated, but it’s the closest cross platform version we have: https://github.com/youwereeatenbyalid/ModCompendium
